// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbmD-SVtpbu40w4mdyQTMOZeNwJpSTPS8',
    appId: '1:273052448154:ios:dbd6b671acaa0391b0f623',
    messagingSenderId: '273052448154',
    projectId: 'time-t-732cb',
    storageBucket: 'time-t-732cb.appspot.com',
    iosBundleId: 'com.example.timet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkByWpoyjyTRSt1Da72PlQ02kvuM1EIuE',
    appId: '1:273052448154:web:02a0a5395c840392b0f623',
    messagingSenderId: '273052448154',
    projectId: 'time-t-732cb',
    authDomain: 'time-t-732cb.firebaseapp.com',
    storageBucket: 'time-t-732cb.appspot.com',
    measurementId: 'G-HN5N9RFPVP',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkByWpoyjyTRSt1Da72PlQ02kvuM1EIuE',
    appId: '1:273052448154:web:02a0a5395c840392b0f623',
    messagingSenderId: '273052448154',
    projectId: 'time-t-732cb',
    authDomain: 'time-t-732cb.firebaseapp.com',
    storageBucket: 'time-t-732cb.appspot.com',
    measurementId: 'G-HN5N9RFPVP',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbmD-SVtpbu40w4mdyQTMOZeNwJpSTPS8',
    appId: '1:273052448154:ios:dbd6b671acaa0391b0f623',
    messagingSenderId: '273052448154',
    projectId: 'time-t-732cb',
    storageBucket: 'time-t-732cb.appspot.com',
    iosBundleId: 'com.example.timet',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6HT4QHr-Gw47qVGHM3nNPvHjzuCd580c',
    appId: '1:273052448154:android:750b76f8bb4d25f7b0f623',
    messagingSenderId: '273052448154',
    projectId: 'time-t-732cb',
    storageBucket: 'time-t-732cb.appspot.com',
  );

}